/**
 * @agentwallet/core — Cloudflare Workers Deployment
 * Deploy vault server as a Cloudflare Worker for edge execution
 */

import { writeFile, mkdir } from "node:fs/promises";
import { join } from "node:path";
import { homedir } from "node:os";
import type { CloudflareConfig, SandboxInstance } from "../types.js";

/**
 * Cloudflare Workers deployment manager.
 */
export class CloudflareDeployer {
  private config: CloudflareConfig;

  constructor(config: CloudflareConfig) {
    this.config = {
      workerName: "agentwallet-vault",
      ...config,
    };
  }

  /**
   * Generate the Worker source code.
   */
  private generateWorkerCode(): string {
    return `
// Auto-generated by @agentwallet/core
import { Vault } from "@agentwallet/core";
import { createVaultRouter, corsMiddleware } from "@agentwallet/core/server";

export default {
  async fetch(request, env, ctx) {
    // Initialize vault with secret passphrase
    const vault = await Vault.create({
      storePath: "/tmp/vault",
      passphrase: env.VAULT_PASSPHRASE,
    });

    // Create Express-like handler
    const router = createVaultRouter(vault);
    
    // Handle CORS
    const corsHandler = corsMiddleware();
    
    return new Promise((resolve) => {
      corsHandler(request, {
        status: () => ({ json: resolve }),
        setHeader: () => {},
        getHeader: () => null,
      }, () => {
        router.handle(request, {
          status: (code) => ({
            json: (data) => resolve(new Response(JSON.stringify(data), {
              status: code,
              headers: { "Content-Type": "application/json" }
            }))
          }),
          json: (data) => resolve(new Response(JSON.stringify(data), {
            headers: { "Content-Type": "application/json" }
          })),
          setHeader: () => {},
          getHeader: () => null,
        }, () => {});
      });
    });
  },
};
`;
  }

  /**
   * Generate wrangler.toml configuration.
   */
  private generateWranglerToml(): string {
    const workerName = this.config.workerName ?? "agentwallet-vault";
    const kvNamespace = this.config.kvNamespace ?? "VAULT_KV";

    return `
name = "${workerName}"
main = "src/worker.js"
compatibility_date = "2024-01-01"

[vars]
ENVIRONMENT = "production"

[[kv_namespaces]]
binding = "${kvNamespace}"
id = "REPLACE_WITH_KV_NAMESPACE_ID"

[triggers]
crons = ["*/5 * * * *"]
`;
  }

  /**
   * Deploy to Cloudflare Workers using wrangler.
   */
  async deploy(): Promise<SandboxInstance> {
    const workerName = this.config.workerName ?? "agentwallet-vault";
    const tempDir = join(homedir(), ".agentwallet", "deploy", workerName);

    try {
      // Create deployment directory
      await mkdir(tempDir, { recursive: true });

      // Write worker source
      await writeFile(join(tempDir, "src", "worker.js"), this.generateWorkerCode());
      await writeFile(join(tempDir, "wrangler.toml"), this.generateWranglerToml());

      // Run wrangler deploy
      const { exec } = await import("node:child_process");
      const { promisify } = await import("node:util");
      const execAsync = promisify(exec);

      // Set secrets
      if (this.config.vaultPassphrase) {
        await execAsync(
          `echo "${this.config.vaultPassphrase}" | wrangler secret put VAULT_PASSPHRASE`,
          { cwd: tempDir, env: { ...process.env, CLOUDFLARE_API_TOKEN: this.config.apiToken } }
        );
      }

      // Deploy
      const { stdout } = await execAsync("npx wrangler deploy", {
        cwd: tempDir,
        env: {
          ...process.env,
          CLOUDFLARE_API_TOKEN: this.config.apiToken,
          CLOUDFLARE_ACCOUNT_ID: this.config.accountId,
        },
      });

      // Parse worker URL from output
      const urlMatch = stdout.match(/https:\/\/[^\s]+\.workers\.dev/);
      const workerUrl = urlMatch?.[0] ?? `https://${workerName}.${this.config.accountId}.workers.dev`;

      console.log(`[Cloudflare] 🚀 Worker deployed: ${workerUrl}`);

      return {
        provider: "cloudflare",
        id: workerName,
        url: workerUrl,
        status: "deployed",
        createdAt: new Date().toISOString(),
        metadata: {
          accountId: this.config.accountId,
          workerName,
        },
      };
    } catch (err) {
      console.error("[Cloudflare] Deployment failed:", err);
      throw new Error(`Cloudflare deployment failed: ${(err as Error).message}`);
    }
  }

  /**
   * Get logs from the deployed worker.
   */
  async logs(): Promise<string> {
    const workerName = this.config.workerName ?? "agentwallet-vault";
    const tempDir = join(homedir(), ".agentwallet", "deploy", workerName);

    try {
      const { exec } = await import("node:child_process");
      const { promisify } = await import("node:util");
      const execAsync = promisify(exec);

      const { stdout } = await execAsync("npx wrangler tail --format json", {
        cwd: tempDir,
        env: {
          ...process.env,
          CLOUDFLARE_API_TOKEN: this.config.apiToken,
          CLOUDFLARE_ACCOUNT_ID: this.config.accountId,
        },
      });

      return stdout;
    } catch (err) {
      throw new Error(`Failed to get logs: ${(err as Error).message}`);
    }
  }
}

/**
 * Deploy to Cloudflare Workers (convenience function).
 */
export async function deployToCloudflare(config: CloudflareConfig): Promise<SandboxInstance> {
  const deployer = new CloudflareDeployer(config);
  return deployer.deploy();
}