FROM rust:1.92 AS builder
WORKDIR /app
COPY Cargo.toml ./
COPY src ./src
RUN cargo build --release

FROM debian:bookworm-slim
ENV III_CONTAINER=docker
ENV III_ENV=development
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates && rm -rf /var/lib/apt/lists/*
COPY --from=builder /app/target/release/compute-worker /app/
WORKDIR /app
CMD ["./compute-worker"]
