export interface HostedSkill {
    id: string;
    name: string;
    category: 'general' | 'pump';
    merchantPath: string;
}

const SKILL_NAMES = [
    '1password',
    'agent-inbox',
    'apple-notes',
    'apple-reminders',
    'artifacts',
    'bear-notes',
    'blogwatcher',
    'blucli',
    'bluebubbles',
    'browse',
    'camsnap',
    'canvas',
    'clawd-vault',
    'clawdhub',
    'clawhub',
    'code_review',
    'coding-agent',
    'cua',
    'database',
    'delegation',
    'deployment',
    'design',
    'design-exploration',
    'diagnostics',
    'discord',
    'e2b',
    'eightctl',
    'environment-secrets',
    'external_apis',
    'follow-up-tasks',
    'gateway-node-ops',
    'gemini',
    'gh-issues',
    'gifgrep',
    'github',
    'gog',
    'goplaces',
    'healthcheck',
    'himalaya',
    'image-search',
    'imsg',
    'integrations',
    'mcporter',
    'media-generation',
    'mockup-extract',
    'mockup-graduate',
    'mockup-sandbox',
    'model-usage',
    'nano-banana-pro',
    'nano-pdf',
    'notion',
    'obsidian',
    'openai-image-gen',
    'openai-whisper',
    'openai-whisper-api',
    'openclaw-claude-code-skill-main',
    'openclawd',
    'openclawd-clawd-code-skill-main',
    'openclawd-code-skill',
    'openclawd-codeskill',
    'openhue',
    'openrouter-oauth',
    'oracle',
    'ordercli',
    'package-management',
    'pdf-to-markdown',
    'peekaboo',
    'post_merge_setup',
    'project_tasks',
    'pump-admin-ops',
    'pump-ai-agents',
    'pump-bonding-curve',
    'pump-build-release',
    'pump-claims-readonly',
    'pump-fee-sharing',
    'pump-fee-system',
    'pump-mcp-server',
    'pump-rust-vanity',
    'pump-sdk-core',
    'pump-security',
    'pump-shell-scripts',
    'pump-solana-architecture',
    'pump-solana-dev',
    'pump-solana-wallet',
    'pump-testing',
    'pump-token-incentives',
    'pump-token-lifecycle',
    'pump-ts-vanity',
    'pump-website',
    'pumpfun-analytics',
    'pumpfun-fees',
    'pumpfun-launcher',
    'pumpfun-token-scanner',
    'pumpfun-trading',
    'query-integration-data',
    'remove-image-background',
    'repl_setup',
    'replit-docs',
    'revenuecat',
    'sag',
    'security_scan',
    'seeker-daemon-ops',
    'session-logs',
    'sherpa-onnx-tts',
    'skill-authoring',
    'skill-creator',
    'slack',
    'solana-attestation-skill',
    'solana-dev-skill-main',
    'solana-formal-verification',
    'solana-research-brief',
    'solanaos',
    'songsee',
    'sonoscli',
    'spotify-player',
    'stripe',
    'summarize',
    'swarm-orchestrator',
    'testing',
    'things-mac',
    'threat_modeling',
    'tmux',
    'trello',
    'validation',
    'video-frames',
    'voice-call',
    'wacli',
    'weather',
    'web-search',
    'workflows',
    'wurk-integration',
    'xurl',
] as const;

function formatSkillName(name: string): string {
    return name
        .replace(/[_-]+/g, ' ')
        .replace(/\b\w/g, (char) => char.toUpperCase());
}

export function getHostedSkills(): HostedSkill[] {
    return SKILL_NAMES.map((name) => ({
        id: name,
        name: formatSkillName(name),
        category: name.startsWith('pump') ? 'pump' : 'general',
        merchantPath: `/skills/${name}`,
    }));
}

export function getHostedSkillSummary() {
    const skills = getHostedSkills();
    return {
        total: skills.length,
        pump: skills.filter((skill) => skill.category === 'pump').length,
        featured: skills.filter((skill) => skill.category === 'pump').slice(0, 8),
    };
}
